import React from 'react';
import {ArrowUpRight,Check,BookOpen,FileCheck,GraduationCap} from 'lucide-react';
export const reviewed='28 September 2026';
export const sources={
 uk:{label:'GOV.UK · Student visa documents',url:'https://www.gov.uk/student-visa/documents-you-must-provide'},
 cas:{label:'GOV.UK · Your course and CAS',url:'https://www.gov.uk/student-visa/course'},
 nz:{label:'Immigration New Zealand · Fee Paying Student Visa',url:'https://www.immigration.govt.nz/visas/fee-paying-student-visa/'},
 kr:{label:'Study in Korea · Student visa and stay status',url:'https://www.studyinkorea.go.kr/en/plan/visaAndStay.do'},
 jp:{label:'Study in Japan / JASSO · Examinations',url:'https://www.studyinjapan.go.jp/en/planning/examination/'},
 jpFees:{label:'Study in Japan / JASSO · Academic fees',url:'https://www.studyinjapan.go.jp/en/planning/academic-fees/'},
 eu:{label:'European Commission · Planning your studies',url:'https://education.ec.europa.eu/study-in-europe/planning-your-studies'},
 noc:{label:'Government of Nepal · Official NOC portal',url:'https://noc.moest.gov.np/'},
 ielts:{label:'IELTS · Academic test format',url:'https://ielts.org/take-a-test/test-types/ielts-academic-test'},
 pte:{label:'Pearson · PTE Academic',url:'https://www.pearsonpte.com/pte-academic'},
 erasmus:{label:'European Commission · Erasmus Mundus Joint Masters',url:'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters'}
};
export function SourceLinks({ids,dated=false}){return <div className="source-links">{dated&&<span className="reviewed">Official guidance · reviewed {reviewed}</span>}{ids.map(id=><a key={id} href={sources[id].url} target="_blank" rel="noopener noreferrer">{sources[id].label} <ArrowUpRight size={14}/><span className="sr-only"> (opens in a new tab)</span></a>)}</div>}
export const destinationInfo={
 KR:{summary:'Degree study or Korean language training: understand the difference before you apply.',tags:['Degree programmes','Language training'],facts:[['Study route','D-2 covers degree programmes; D-4 covers non-degree training, including Korean language training.'],['Before applying','Obtain an admission letter, identify the appropriate visa category, and check the embassy’s current instructions.'],['Evidence to prepare','The official guide lists identity, admission, education and financial evidence. Additional documents depend on the programme and applicant.']],questions:['What is the teaching language of my chosen course?','Which language result does the institution accept?','What are the tuition, housing and application deadlines?'],ids:['kr']},
 UK:{summary:'Start with your course choice, then understand the offer, CAS and visa documentation.',tags:['Course selection','CAS & visa documents'],facts:[['Study route','The Student visa route requires an unconditional place with a licensed student sponsor and a Confirmation of Acceptance for Studies (CAS).'],['Before applying','Your provider issues the CAS reference. An ordinary offer letter is not a replacement for this visa application reference.'],['Evidence to prepare','A current passport or valid travel document and CAS are required. Financial evidence, TB results, ATAS or parental consent may also apply to your circumstances.']],questions:['Does my course match my previous study and goals?','What conditions must I meet before a CAS is issued?','What are the deposit, refund and total cost terms?'],ids:['cas','uk']},
 NZ:{summary:'Understand the offer of place, funding and insurance requirements for full-time study.',tags:['Approved provider','Funding & insurance'],facts:[['Study route','The Fee Paying Student Visa supports full-time study on an approved course with an approved education provider.'],['Before applying','Prepare your offer of place and evidence of tuition and living-cost funding. You must also meet health, character and other visa requirements.'],['Insurance & timing','Medical and travel insurance must meet the relevant requirements. Immigration New Zealand advises applying at least three months before planned travel.']],questions:['Is the provider approved for my intended study?','How will I document tuition and living-cost funding?','What insurance and accommodation arrangements are needed?'],ids:['nz']},
 EU:{summary:'Choose a country first: Europe has different admission, visa and funding systems.',tags:['Country-specific rules','Course & funding research'],facts:[['Study route','Compare the country, institution, qualification and teaching language. There is no single admission process for all of Europe.'],['Before applying','Use the European Commission’s country profiles and the destination’s official immigration guidance to investigate student visas or residence permits.'],['Plan beyond tuition','Research living costs, accommodation and insurance. Health-insurance obligations differ by country; check the national guidance.']],questions:['Which European countries does ASTRA currently support?','Is the programme taught in a language I meet the requirements for?','Which national visa and residence rules apply to my course?'],ids:['eu']},
 JP:{summary:'Check the school’s teaching language and entrance examinations well before applying.',tags:['School requirements','Language & EJU'],facts:[['Study route','Your school’s admissions guidelines determine the examinations you need. Check these before choosing a language or test-preparation route.'],['Entrance examinations','Some universities use the Examination for Japanese University Admission for International Students (EJU). Required subjects and accepted test sittings are set by the institution.'],['Budget preparation','Fees differ by institution and programme. Besides tuition and admission fees, account for examination fees, learning materials and any practical training charges.']],questions:['Which examinations and language evidence does my school require?','When can I take the required exam and apply?','What fees are payable before and after admission?'],ids:['jp','jpFees']}
};
export const services=[
 {Icon:GraduationCap,n:'01',title:'Study abroad',intro:'Turn a broad ambition into a considered study plan. Begin with your academic history, interests, budget and preferred destinations.',points:['Compare the course content, qualification and teaching language.','Review published entry criteria and application deadlines.','Plan tuition, living costs and the questions to ask each institution.'],detail:'Bring your highest qualification, subject interests and a realistic funding outline to your first conversation. Ask for confirmation of the institutions and services ASTRA currently supports.',cta:'Discuss my study options',subject:'Study abroad planning'},
 {Icon:FileCheck,n:'02',title:'Visa guidance',intro:'Understand how your proposed study connects to the relevant visa route, and which evidence the responsible authority asks you to provide.',points:['Identify the visa route for your course and destination.','Review official document requirements and any individual conditions.','Keep names, dates and supporting information consistent and accurate.'],detail:'An admission offer and a visa are separate decisions. Always use the latest official instructions, genuine documents and the authority’s own application channels.',cta:'Discuss visa preparation',subject:'Visa guidance'},
 {Icon:BookOpen,n:'03',title:'Language preparation',intro:'Your language plan should start with the requirements of the course you want to enter—not a generic target score.',points:['Check the accepted test, version and minimum component scores.','Compare your current level with the institution’s requirements.','Allow time for preparation, testing and application deadlines.'],detail:'Ask ASTRA which classes, tests and schedules are currently available. The test explainers below are general information and do not imply that every course is offered by ASTRA.',cta:'Ask about available classes',subject:'Language preparation'}
];
export function Preparation({onEnquire}){return <>
<section id="preparation" className="section wrap preparation"><div className="section-heading"><div><div className="eyebrow">PREPARE WITH PURPOSE</div><h2>A stronger plan starts<br/>with the right questions.</h2></div><p>Use these discussion guides to prepare.<br/>Entry criteria are set by each institution.</p></div><div className="planning-grid">{[
 ['01','Undergraduate study','For students exploring their next step after higher secondary education.',['Compare your prior subjects with course prerequisites.','Check the qualification awarded, teaching language and assessment style.','Ask about entry requirements, total duration and progression options.'],'Undergraduate study'],
 ['02','Postgraduate study','For graduates considering a more specialised academic direction.',['Check whether your degree and subject background are accepted.','Review research, portfolio or work-experience requirements where relevant.','Compare course modules, supervisor fit and funding options.'],'Postgraduate study'],
 ['03','Language readiness','For students working towards the language demands of their intended course.',['Confirm the exact test and version the institution accepts.','Check minimum overall and individual skill requirements.','Plan preparation and test dates around the application deadline.'],'Language preparation']
].map(([n,t,p,items,subject])=><article key={n} className="planning-card"><span className="planning-num">{n}</span><h3>{t}</h3><p>{p}</p><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><a href="#contact" className="text-link" onClick={()=>onEnquire(subject)}>Discuss this pathway <ArrowUpRight size={16}/></a></article>)}</div>
<div className="test-explainers"><div><div className="eyebrow">KNOW THE TEST</div><h3>Preparation begins with the format.</h3><p>Confirm your institution’s accepted test and score before booking. ASTRA’s current class availability must be confirmed with the team.</p></div><article><h4>IELTS Academic</h4><p>Assesses listening, reading, writing and speaking. Academic and General Training share listening and speaking formats; reading and writing differ.</p><SourceLinks ids={['ielts']}/></article><article><h4>PTE Academic</h4><p>A computer-based academic English test covering speaking, writing, reading and listening. Check the accepted version and score with your institution.</p><SourceLinks ids={['pte']}/></article></div></section>
<section id="resources" className="section resource-section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">INFORMATION YOU CAN CHECK</div><h2>Before you apply.<br/>Before you commit.</h2></div><p>Practical preparation for students in Nepal,<br/>with links to the original official guidance.</p></div><div className="resource-grid"><article className="resource-card"><span className="resource-category">NEPAL · NOC</span><h3>Understand your No Objection Certificate.</h3><p>Nepal’s official NOC portal is the starting point for the government’s certificate for Nepali students studying abroad. Review the instructions for your course and circumstances.</p><ul><li>Check the current document list and application process.</li><li>Have academic and admission information ready for review.</li><li>Use the official portal; requirements can differ by study route.</li></ul><SourceLinks ids={['noc']} dated/></article><article className="resource-card"><span className="resource-category">FUNDING · SCHOLARSHIPS</span><h3>Research funding with the provider.</h3><p>Erasmus Mundus Joint Masters accept applicants worldwide. Some programmes offer competitive full scholarships; students apply to the institution running the programme.</p><ul><li>Check the individual programme’s academic eligibility.</li><li>Read the scholarship coverage and selection conditions.</li><li>Verify the current deadline on the programme’s own website.</li></ul><SourceLinks ids={['erasmus']} dated/></article><article className="resource-card"><span className="resource-category">PLANNING · TOTAL COST</span><h3>Look beyond the tuition figure.</h3><p>Build a written budget using official fee schedules and current provider information. Research accommodation and insurance before committing to a course.</p><ul><li>Tuition, application and enrolment charges.</li><li>Housing, food, travel and required insurance.</li><li>Visa, test and document-related costs, plus a contingency.</li></ul><SourceLinks ids={['eu','jpFees']} dated/></article></div><div className="evidence-note"><FileCheck size={21}/><p><strong>Read the source. Check the date.</strong> These are planning summaries, not an eligibility decision. Fees, rules and deadlines can change. Official links are provided for verification and do not imply endorsement or partnership with ASTRA.</p></div></div></section>
<section className="section wrap checklist-section"><div><div className="eyebrow">MAKE THE FIRST CONVERSATION USEFUL</div><h2>Bring your goals.<br/>Prepare the essentials.</h2><p>This is a counselling preparation list, not a universal visa checklist. Your institution and immigration authority determine the final evidence required.</p><a href="#contact" className="button" onClick={()=>onEnquire('First counselling session')}>Plan my counselling session <ArrowUpRight size={17}/></a></div><div className="checklist-items">{[['Academic background','Your highest qualification, subjects, grades and any study gaps you want to discuss.'],['Study preferences','Two or three subject interests, preferred destinations and intended level of study.'],['Language background','Any existing test results and the teaching language you are preparing for.'],['Funding outline','Your approximate budget, funding source and the costs you still need to clarify.'],['Questions for the team','Current service scope, charges, timelines, document handling and next steps.']].map(([t,p])=><div key={t}><span><Check size={17}/></span><div><h3>{t}</h3><p>{p}</p></div></div>)}<small>Share sensitive documents only through a channel you have verified with the team.</small></div></section>
</>}
